/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: carlosortega3d (https://sketchfab.com/carlosortega3d)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/cybertruck-fun-size-6d5e91d7acee4b42af045531245774ca
Title: Cybertruck - Fun Size
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.13}>
          <group name="46b0c278255a4327a11ed74bb747239dfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="ball01" position={[22.13, 0.58, 3.25]} rotation={[0, 0, -1.51]} scale={0.44}>
                  <mesh name="ball01_ball_0" geometry={nodes.ball01_ball_0.geometry} material={materials.ball} />
                </group>
                <group name="ball02" position={[20.85, 0.58, -0.36]} rotation={[0, 0, -1.51]} scale={0.44}>
                  <mesh name="ball02_ball_0" geometry={nodes.ball02_ball_0.geometry} material={materials.ball} />
                </group>
                <group name="cybertruck_mini_grp">
                  <group name="top_body" position={[0, 5.94, 0]}>
                    <group name="glass_break3" position={[7.3, 6.08, 3.21]}>
                      <mesh name="glass_break3_glass_02_0" geometry={nodes.glass_break3_glass_02_0.geometry} material={materials.glass_02} />
                    </group>
                    <group name="glass_break4" position={[6.59, 7.9, -0.43]}>
                      <mesh name="glass_break4_glass_02_0" geometry={nodes.glass_break4_glass_02_0.geometry} material={materials.glass_02} />
                    </group>
                    <group name="lower_body" position={[0, -6.08, 0]}>
                      <mesh name="lower_body_body_low_shd_0" geometry={nodes.lower_body_body_low_shd_0.geometry} material={materials.body_low_shd} />
                    </group>
                    <group name="stop_lights" position={[0, -6.08, 0]}>
                      <mesh name="stop_lights_backlight_shd_0" geometry={nodes.stop_lights_backlight_shd_0.geometry} material={materials.backlight_shd} />
                    </group>
                    <group name="headlights" position={[0, -6.08, 0]}>
                      <mesh name="headlights_headlights_shd_0" geometry={nodes.headlights_headlights_shd_0.geometry} material={materials.headlights_shd} />
                    </group>
                    <group name="low_lights" position={[0, -6.08, 0]}>
                      <mesh name="low_lights_lowlights_shd_0" geometry={nodes.low_lights_lowlights_shd_0.geometry} material={materials.lowlights_shd} />
                    </group>
                    <group name="bottom_body" position={[0, -6.08, 0]}>
                      <mesh name="bottom_body_body_low_shd_0" geometry={nodes.bottom_body_body_low_shd_0.geometry} material={materials.body_low_shd} />
                    </group>
                    <group name="seats" position={[0, 4.91, 2.51]}>
                      <mesh name="seats_body_low_shd_0" geometry={nodes.seats_body_low_shd_0.geometry} material={materials.body_low_shd} />
                    </group>
                    <group name="body" position={[0, -5.94, 0]}>
                      <mesh name="body_body_shd_0" geometry={nodes.body_body_shd_0.geometry} material={materials.body_shd} />
                    </group>
                    <group name="glass2" position={[0, -5.94, 0]}>
                      <mesh name="glass2_glass_01_0" geometry={nodes.glass2_glass_01_0.geometry} material={materials.glass_01} />
                    </group>
                  </group>
                  <group name="tire_front_L">
                    <group name="tire">
                      <mesh name="tire_tires_shd_0" geometry={nodes.tire_tires_shd_0.geometry} material={materials.tires_shd} />
                    </group>
                    <group name="tire_threads">
                      <mesh name="tire_threads_tires_shd_0" geometry={nodes.tire_threads_tires_shd_0.geometry} material={materials.tires_shd} />
                    </group>
                    <group name="rim">
                      <mesh name="rim_rims_shd_0" geometry={nodes.rim_rims_shd_0.geometry} material={materials.rims_shd} />
                    </group>
                  </group>
                  <group name="tire_back_L">
                    <group name="tire_1">
                      <mesh name="tire_tires_shd_0_1" geometry={nodes.tire_tires_shd_0_1.geometry} material={materials.tires_shd} />
                    </group>
                    <group name="tire_threads_1">
                      <mesh name="tire_threads_tires_shd_0_1" geometry={nodes.tire_threads_tires_shd_0_1.geometry} material={materials.tires_shd} />
                    </group>
                    <group name="rim_1">
                      <mesh name="rim_rims_shd_0_1" geometry={nodes.rim_rims_shd_0_1.geometry} material={materials.rims_shd} />
                    </group>
                  </group>
                  <group name="tire_back_R">
                    <group name="tire_2">
                      <mesh name="tire_tires_shd_0_2" geometry={nodes.tire_tires_shd_0_2.geometry} material={materials.tires_shd} />
                    </group>
                    <group name="tire_threads_2">
                      <mesh name="tire_threads_tires_shd_0_2" geometry={nodes.tire_threads_tires_shd_0_2.geometry} material={materials.tires_shd} />
                    </group>
                    <group name="rim_2">
                      <mesh name="rim_rims_shd_0_2" geometry={nodes.rim_rims_shd_0_2.geometry} material={materials.rims_shd} />
                    </group>
                  </group>
                  <group name="tire_front_R">
                    <group name="tire_3">
                      <mesh name="tire_tires_shd_0_3" geometry={nodes.tire_tires_shd_0_3.geometry} material={materials.tires_shd} />
                    </group>
                    <group name="tire_threads_3">
                      <mesh name="tire_threads_tires_shd_0_3" geometry={nodes.tire_threads_tires_shd_0_3.geometry} material={materials.tires_shd} />
                    </group>
                    <group name="rim_3">
                      <mesh name="rim_rims_shd_0_3" geometry={nodes.rim_rims_shd_0_3.geometry} material={materials.rims_shd} />
                    </group>
                  </group>
                  <group name="lights_truck_grp">
                    <group name="aiAreaLight5" position={[7.53, 8.93, 14.4]} rotation={[-2.7, -0.02, -3.13]} />
                    <group name="aiAreaLight6" position={[-7.5, 8.93, 14.73]} rotation={[-2.7, -0.02, -3.13]} />
                    <group name="aiAreaLight7" position={[0.17, 11.14, -14.89]} rotation={[-0.13, 0, 0]} scale={[6.96, 0.48, 1]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
